<a href="https://colab.research.google.com/github/birendradhami777/AI-Lab-Report/blob/main/Machinelearning(lab4)388.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#AND GATE
import numpy as np

def perceptron_AND():
    inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
    outputs = np.array([0, 0, 0, 1])  # AND Gate
    weights = np.random.rand(2)
    bias = np.random.rand(1)
    lr = 0.1  # Learning rate

    for epoch in range(10):
        for i, x in enumerate(inputs):
            y = np.dot(x, weights) + bias
            prediction = 1 if y > 0 else 0
            error = outputs[i] - prediction
            weights += lr * error * x
            bias += lr * error

    return weights, bias

weights, bias = perceptron_AND()
print(f"Trained weights: {weights}, Bias: {bias}")


Trained weights: [0.19231927 0.02352978], Bias: [-0.19277694]


In [2]:
#OR GATE
def perceptron_OR():
    inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
    outputs = np.array([0, 1, 1, 1])  # OR Gate
    weights = np.random.rand(2)
    bias = np.random.rand(1)
    lr = 0.1

    for epoch in range(10):
        for i, x in enumerate(inputs):
            y = np.dot(x, weights) + bias
            prediction = 1 if y > 0 else 0
            error = outputs[i] - prediction
            weights += lr * error * x
            bias += lr * error

    return weights, bias

weights, bias = perceptron_OR()
print(f"Trained weights: {weights}, Bias: {bias}")


Trained weights: [0.845954   0.15967053], Bias: [-0.01643344]


In [ ]:
#XOR GATE
from sklearn.neural_network import MLPClassifier

def perceptron_XOR():
    inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
    outputs = np.array([0, 1, 1, 0])  # XOR Gate
    model = MLPClassifier(hidden_layer_sizes=(2,), activation='relu', max_iter=1000)
    model.fit(inputs, outputs)
    return model

model = perceptron_XOR()
print("Trained XOR perceptron.")


Trained XOR perceptron.


/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:
#NOT GATE
def perceptron_NOT():
    inputs = np.array([0, 1])
    outputs = np.array([1, 0])  # NOT Gate
    weights = np.random.rand(1)
    bias = np.random.rand(1)
    lr = 0.1

    for epoch in range(10):
        for i, x in enumerate(inputs):
            y = x * weights + bias
            prediction = 1 if y > 0 else 0
            error = outputs[i] - prediction
            weights += lr * error * x
            bias += lr * error

    return weights, bias

weights, bias = perceptron_NOT()
print(f"Trained weights: {weights}, Bias: {bias}")


Trained weights: [-0.10240394], Bias: [0.06939302]


In [ ]:
#K Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier

def kNN():
    # Example dataset
    inputs = [[1, 1], [1, 2], [2, 2], [2, 3], [3, 3]]
    outputs = [0, 0, 1, 1, 1]  # Labels
    model = KNeighborsClassifier(n_neighbors=3)
    model.fit(inputs, outputs)
    return model

model = kNN()
print("Trained kNN model.")


Trained kNN model.


In [ ]:
#Support vector system
from sklearn.svm import SVC

def SVM():
    inputs = [[1, 1], [1, 2], [2, 2], [2, 3], [3, 3]]
    outputs = [0, 0, 1, 1, 1]
    model = SVC(kernel='linear')
    model.fit(inputs, outputs)
    return model

model = SVM()
print("Trained SVM model.")


Trained SVM model.


In [ ]:
#K Means Clustering
from sklearn.cluster import KMeans

def kMeans():
    inputs = [[1, 1], [1, 2], [2, 2], [2, 3], [3, 3], [10, 10], [10, 11]]
    model = KMeans(n_clusters=2, random_state=0)
    model.fit(inputs)
    return model

model = kMeans()
print("Trained k-Means clustering model.")


Trained k-Means clustering model.


In [ ]:
#Perception for odd and even numbers
def perceptron_odd_even():
    inputs = np.array([[0], [1], [2], [3], [4]])
    outputs = np.array([0, 1, 0, 1, 0])  # Even: 0, Odd: 1
    weights = np.random.rand(1)
    bias = np.random.rand(1)
    lr = 0.1

    for epoch in range(20):
        for i, x in enumerate(inputs):
            y = x * weights + bias
            prediction = 1 if y > 0.5 else 0
            error = outputs[i] - prediction
            weights += lr * error * x
            bias += lr * error

    return weights, bias

weights, bias = perceptron_odd_even()
print(f"Trained weights: {weights}, Bias: {bias}")


Trained weights: [-0.3293323], Bias: [0.55029216]


In [ ]:
#BAM
def BAM(ids, numbers):
    memory = {}
    for i, id_ in enumerate(ids):
        memory[id_] = numbers[i]
    return memory

ids = ['A', 'B', 'C']
numbers = ['123', '456', '789']
memory = BAM(ids, numbers)
print(memory)


{'A': '123', 'B': '456', 'C': '789'}


In [ ]:
#HopField Network
import numpy as np

def Hopfield():
    patterns = np.array([[-1, 1, -1], [1, -1, 1]])  # Example patterns
    num_neurons = patterns.shape[1]

    # Compute weight matrix
    weights = np.zeros((num_neurons, num_neurons))
    for pattern in patterns:
        weights += np.outer(pattern, pattern)
    np.fill_diagonal(weights, 0)  # No self-connections

    def recall(input_pattern):
        input_pattern = np.array(input_pattern)
        output = input_pattern.copy()
        for _ in range(10):  # Iterate for convergence
            output = np.sign(np.dot(weights, output))
        return output

    return weights, recall

weights, recall = Hopfield()
test_pattern = [-1, 1, -1]
recalled_pattern = recall(test_pattern)

print("Weights matrix:")
print(weights)
print("Input pattern:", test_pattern)
print("Recalled pattern:", recalled_pattern)


Weights matrix:
[[ 0. -2.  2.]
 [-2.  0. -2.]
 [ 2. -2.  0.]]
Input pattern: [-1, 1, -1]
Recalled pattern: [-1.  1. -1.]
